/* DAY 03 PRACTICE SETS — synthetic educational data */

DATA DM_RAW;
    INPUT SUBJID $ AGE SEX $ RACE $ COUNTRY $ SITE $ STATUS $;
    DATALINES;
1001 25 M ASIAN INDIA S01 ACTIVE
1002 31 F WHITE INDIA S02 ACTIVE
1003 66 M ASIAN INDIA S01 ACTIVE
1004 17 F ASIAN INDIA S03 SCREENED
1005 52 M WHITE INDIA S02 ACTIVE
;
RUN;

/* IF / ELSE */
DATA DM_CLASSIFIED;
    SET DM_RAW;
    IF AGE >= 18 THEN ELIGIBLE = "Y";
    ELSE ELIGIBLE = "N";
RUN;

/* WHERE + KEEP */
DATA DM_ADULT;
    SET DM_RAW;
    WHERE AGE >= 18;
    KEEP SUBJID AGE SEX RACE;
RUN;

/* Observation count */
PROC SQL;
    SELECT COUNT(*) AS N
    FROM DM_RAW;
QUIT;

/* Sort and inspect duplicate keys */
PROC SORT DATA=DM_RAW OUT=DM_SORTED;
    BY SUBJID;
RUN;

/* MERGE concept */
PROC SORT DATA=DM_RAW; BY SUBJID; RUN;
PROC SORT DATA=DM_CLASSIFIED; BY SUBJID; RUN;

DATA DM_COMBINED;
    MERGE DM_RAW DM_CLASSIFIED;
    BY SUBJID;
RUN;

PROC PRINT DATA=DM_COMBINED;
RUN;

/* Day 3 practice focused on:
   conditions, WHERE vs IF, KEEP/DROP,
   counting, MERGE/JOIN concepts,
   duplicate/key validation and debugging.
*/