/* DAY 01 PRACTICE SETS — synthetic educational data */

DATA DM_RAW;
    INPUT SUBJID $ AGE SEX $ RACE $ COUNTRY $ SITE $;
    DATALINES;
1001 25 M ASIAN INDIA S01
1002 31 F WHITE INDIA S02
1003 40 M ASIAN INDIA S01
1004 17 F ASIAN INDIA S03
1005 70 M WHITE INDIA S02
;
RUN;

PROC PRINT DATA=DM_RAW;
RUN;

PROC CONTENTS DATA=DM_RAW;
RUN;

PROC FREQ DATA=DM_RAW;
    TABLES SEX RACE COUNTRY SITE;
RUN;

PROC MEANS DATA=DM_RAW;
    VAR AGE;
RUN;

/* Day 1 concept practice:
   RAW data → SDTM → ADaM → TLFs
   DATA creates/modifies datasets; PROC performs procedures.
*/