/* ============================================================
   DAY 06 — SAS CHARACTER SEARCH & COUNT FUNCTIONS
   Clinical SAS Journey — Avinash Rai
   Synthetic educational data only
   ============================================================ */

/* Task 1 — ANYALPHA */
DATA SDTM.DM ;
    SET RAW.DM ;
    SITE_ALPHA_POS=ANYALPHA(SITE) ;
    KEEP SUBJID SITE SITE_ALPHA_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 2 — ANYSPACE */
DATA SDTM.DM ;
    SET RAW.DM ;
    SPACE_POS=ANYSPACE(COUNTRY) ;
    KEEP SUBJID COUNTRY SPACE_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 3 — NOTDIGIT */
DATA SDTM.DM ;
    SET RAW.DM ;
    SITE_NONDIGIT_POS=NOTDIGIT(SITE) ;
    KEEP SUBJID SITE SITE_NONDIGIT_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 4 — NOTALPHA */
DATA SDTM.DM ;
    SET RAW.DM ;
    SITE_NONALPHA_POS=NOTALPHA(SITE) ;
    KEEP SUBJID SITE SITE_NONALPHA_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 5 — NOTSPACE */
DATA SDTM.DM ;
    SET RAW.DM ;
    COUNTRY_FIRSTCHAR_POS=NOTSPACE(COUNTRY) ;
    KEEP SUBJID COUNTRY COUNTRY_FIRSTCHAR_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 6 — ANYUPPER */
DATA SDTM.DM ;
    SET RAW.DM ;
    COUNTRY_UPPER_POS=ANYUPPER(COUNTRY) ;
    KEEP SUBJID COUNTRY COUNTRY_UPPER_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 7 — ANYLOWER */
DATA SDTM.DM ;
    SET RAW.DM ;
    COUNTRY_LOWER_POS=ANYLOWER(COUNTRY) ;
    KEEP SUBJID COUNTRY COUNTRY_LOWER_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 8 — NOTUPPER */
DATA SDTM.DM ;
    SET RAW.DM ;
    COUNTRY_NOTUPPER_POS=NOTUPPER(COUNTRY) ;
    KEEP SUBJID COUNTRY COUNTRY_NOTUPPER_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 9 — NOTLOWER */
DATA SDTM.DM ;
    SET RAW.DM ;
    COUNTRY_NOTLOWER_POS=NOTLOWER(COUNTRY) ;
    KEEP SUBJID COUNTRY COUNTRY_NOTLOWER_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 10 — VERIFY */
DATA SDTM.DM ;
    SET RAW.DM ;
    SITE_VERIFY_POS=VERIFY(SITE,"ABCDEFGHIJKLMNOPQRSTUVWXYZ") ;
    KEEP SUBJID SITE SITE_VERIFY_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 11 — ANYALNUM */
DATA SDTM.DM ;
    SET RAW.DM ;
    SITE_ALNUM_POS=ANYALNUM(SITE) ;
    KEEP SUBJID SITE SITE_ALNUM_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 12 — NOTALNUM */
DATA SDTM.DM ;
    SET RAW.DM ;
    SITE_NOTALNUM_POS=NOTALNUM(SITE) ;
    KEEP SUBJID SITE SITE_NOTALNUM_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 13 — ANYXDIGIT */
DATA SDTM.DM ;
    SET RAW.DM ;
    SITE_HEX_POS=ANYXDIGIT(SITE) ;
    KEEP SUBJID SITE SITE_HEX_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 14 — NOTXDIGIT */
DATA SDTM.DM ;
    SET RAW.DM ;
    SITE_NOTHEX_POS=NOTXDIGIT(SITE) ;
    KEEP SUBJID SITE SITE_NOTHEX_POS ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 15 — COUNT */
DATA SDTM.DM ;
    SET RAW.DM ;
    COUNTRY_I_COUNT=COUNT(COUNTRY,"I") ;
    KEEP SUBJID COUNTRY COUNTRY_I_COUNT ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;


/* Task 16 — COUNTC */
DATA SDTM.DM ;
    SET RAW.DM ;
    COUNTRY_VOWEL_COUNT=COUNTC(COUNTRY,"AEIOU") ;
    KEEP SUBJID COUNTRY COUNTRY_VOWEL_COUNT ;
RUN ;
PROC PRINT DATA=SDTM.DM ;
RUN ;
